version: 1.0.{build}
branches:
  only:
  - master
skip_tags: true
configuration: Release
platform: Any CPU
nuget:
  account_feed: true
  project_feed: true
before_build:
- cmd: -nuget restore
build:
  publish_wap: true
  verbosity: minimal
deploy:
- provider: GitHub
  auth_token:
    secure: JUYzw0XWbwKyC0oXr5n8gITHK557qvwCDRa3lnHFdXJqNg3rS/NQqmYwoDpI58m2
