version: 2.0.{build}
branches:
  only:
  - master
skip_tags: true
os: Visual Studio 2015
configuration: Release
platform: Any CPU
assembly_info:
  patch: true
  file: '**\AssemblyInfo.*'
  assembly_version: 2.0.{build}
  assembly_file_version: '{version}'
  assembly_informational_version: '{version}'
nuget:
  account_feed: true
  project_feed: true
before_build:
- cmd: >-
    appveyor DownloadFile https://dist.nuget.org/win-x86-commandline/v3.2.0-rc/nuget.exe

    appveyor DownloadFile https://raw.githubusercontent.com/appveyor/ci/master/scripts/nuget-restore.cmd

    nuget-restore
build:
  publish_wap: true
  publish_nuget: true
  publish_nuget_symbols: true
  include_nuget_references: true
  parallel: true
  verbosity: minimal
test:
  assemblies: Advokatforeningen.Archive.Api.Tests.dll
  categories:
    only:
    - GetCaseFolderDetails
    - CreateCaseFolders
artifacts:
- path: Advokatforeningen.Archive.Api.zip
  name: Release
  type: WebDeployPackage
deploy:
- provider: GitHub
  auth_token:
    secure: JUYzw0XWbwKyC0oXr5n8gITHK557qvwCDRa3lnHFdXJqNg3rS/NQqmYwoDpI58m2
  artifact: 
  on:
    branch: master
on_success:
- ps: "$apiUrl = 'https://ci.appveyor.com/api'\n$token = '549057cd5a7f5bd4f3841b4d3d4b925e4e2f2f83'  #'f6c72913832a5c10ca8cea33230657d4d0a89d9c'\n$headers = @{\n  \"Authorization\" = \"Bearer $token\"\n  #\"Content-Type\" = \"application/json\" #\"text/x-gwt-rpc; charset=utf-8\" # \"application/x-www-form-urlencoded\" #\n  #\"Accept\" = \"application/xml\"\n}\n$accountName = 'vikasbansal9888' #'pooja.dhingra@spanservices.com'#'PoojaDhingra'\n$projectSlug = 'advokatforeningen-archive-api'  #'Advokatforeningen.Archive.Api'\n\n#$credenials = ''\n\n$downloadLocation = 'C:\\Users\\spsetup\\Desktop\\Pooja' #'C:\\projects'\n\n# get project with last build details\n$project = Invoke-RestMethod -Method Get -Uri \"$apiUrl/projects/$accountName/$projectSlug\"  -Headers $headers\n#$project\n\n#   87m6677sq3jcyloe\n\n\n# we assume here that build has a single job\n# get this job id\n$jobId = $project.build.jobs[0].jobId\n#$jobId\n\n\n\n# get job artifacts (just to see what we've got)\n$artifacts = Invoke-RestMethod -Method Get -Uri \"$apiUrl/buildjobs/$jobId/artifacts\" -Headers $headers\n#$artifacts\n\n# here we just take the first artifact, but you could specify its file name\n# $artifactFileName = 'MyWebApp.zip'\n$artifactFileName = $artifacts[0].fileName\n\n# artifact will be downloaded as \n$localArtifactPath = \"$downloadLocation\\$artifactFileName\"\n\n# download artifact\n# -OutFile - is local file name where artifact will be downloaded into\nInvoke-RestMethod -Method Get -Uri \"$apiUrl/buildjobs/$jobId/artifacts/$artifactFileName\" `\n     -OutFile $localArtifactPath -Headers $headers"
