version: 2.0.{build}
branches:
  only:
  - master
skip_tags: true
os: Visual Studio 2015
configuration: Release
platform: Any CPU
assembly_info:
  patch: true
  file: '**\AssemblyInfo.*'
  assembly_version: 2.0.{build}
  assembly_file_version: '{version}'
  assembly_informational_version: '{version}'
nuget:
  account_feed: true
  project_feed: true
before_build:
- cmd: >-
    appveyor DownloadFile https://dist.nuget.org/win-x86-commandline/v3.2.0-rc/nuget.exe

    appveyor DownloadFile https://raw.githubusercontent.com/appveyor/ci/master/scripts/nuget-restore.cmd

    nuget-restore
build:
  publish_wap: true
  publish_nuget: true
  publish_nuget_symbols: true
  include_nuget_references: true
  parallel: true
  verbosity: minimal
before_test:
- cmd: vstest.console /logger:Appveyor '**\*.Advokatforeningen.Archive.Api.dll'
artifacts:
- path: Advokatforeningen.Archive.Api.zip
  name: Release
  type: WebDeployPackage
deploy:
- provider: GitHub
  auth_token:
    secure: JUYzw0XWbwKyC0oXr5n8gITHK557qvwCDRa3lnHFdXJqNg3rS/NQqmYwoDpI58m2
  artifact: 
  on:
    branch: master
