version: 1.0.{build}
branches:
  only:
  - master
skip_tags: true
configuration: Release
platform: Any CPU
nuget:
  account_feed: true
  project_feed: true
before_build:
- ps: -nuget restore
build:
  publish_wap: true
  verbosity: minimal
